import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	// PRD N5: the release must be main.js/manifest.json/styles.css only.
	// ghostty-web 0.4.0 already carries ghostty-vt.wasm as an inline
	// `data:application/wasm;base64,…` literal and fetches that data URL, so no
	// wasm file is emitted today (notes/ghostty-web.md). This loader entry keeps
	// that true if a future ghostty-web imports the .wasm asset instead: esbuild
	// would inline it as a data URL rather than write a sibling file. If the
	// bundle ever stops containing `data:application/wasm;base64`, the wasm is no
	// longer embedded — fail the release rather than shipping a loose file.
	loader: {
		'.wasm': 'dataurl',
	},
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
